[package]
name = "deep-bubocore"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
priority-queue = "2.1.2"
=======
midir = "0.10.1"
rosc = "0.10.1"
rusty_link = "0.4.4"
thread-priority = "1.2.0"
>>>>>>> 509248a2c788439c84a771ab84778a7992100361

[lib]
name = "bubocoreserver"
path = "src/lib.rs"
